# Imports

In [1]:
import pandas as pd
from pathlib import Path

# Nettoyage du dataframe ERA5 mensuel

In [2]:
ERA5_monthly_raw_path = Path('/home/ec2-user/SageMaker/EtudeWindIndex/Data/ERA5/ERA5_monthly/Raw/ERA5_monthly.csv')
ERA5_monthly_path = Path('/home/ec2-user/SageMaker/EtudeWindIndex/Data/ERA5/ERA5_monthly/Clean/ERA5_monthly.csv')

In [3]:
#Lecture de l'export mensuel de ERA5
era5 = pd.read_csv(ERA5_monthly_raw_path, sep=';')
era5['date'] = pd.to_datetime(era5['period'])

#Visualisation
era5.head()

,project_code,period,wind_speed_100m,direction_100m,temperature_2m,pressure,air_density,relative_humidity,precipitation,snowfall,solar_radiation,energy_100m,energy_100m_density_corr,date
0,AUQB,2000-01,6.2,316.0,7.0,100925.0,1.26,78.0,0.029,0.001,58756.0,86972.0,88915.0,2000-01-01
1,AMEL,2000-01,6.2,218.0,2.0,99538.0,1.26,91.0,0.052,0.003,28493.0,74058.0,75129.0,2000-01-01
2,BOUS,2000-01,5.9,204.0,2.0,99510.0,1.26,90.0,0.047,0.001,26949.0,68181.0,68956.0,2000-01-01
3,BRIY,2000-01,6.6,204.0,4.0,101149.0,1.27,91.0,0.040,0.003,26518.0,89995.0,92293.0,2000-01-01
4,CLIT,2000-01,9.2,208.0,8.0,102479.0,1.27,83.0,0.041,0.000,31961.0,170361.0,175841.0,2000-01-01

In [4]:
#Sauvegarde
era5.to_csv(ERA5_monthly_path, index=False, sep=';')