# Imports

In [9]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

# Fonction de création de set

In [10]:
def real_tts(project):
    
    #Lecture de l'export 10min du projet
    S3_bucket = 'edfred-edfre-sbx-eu-west-1-solar-radiation-data'
    S3_real_folder = r'EtudeWindIndex/Real'
    file = '10min_' + project
    S3_real = f's3://{S3_bucket}/{S3_real_folder}/{file}.csv'
    real_set = pd.read_csv(S3_real, sep=';')
    
    #Fabrication du trainset et testset
    #Stratifié par turbine et par heure !
    trainset, testset = train_test_split(real_set, test_size=0.33, random_state=42, stratify=real_set.loc[:,['turbine','year','month','day','hour']])
    
    #Sauvegarde
    trainset_path = Path('/home/ec2-user/SageMaker/EtudeWindIndex/Data/Train_Test/hourly/trainset.csv')
    testset_path = Path('/home/ec2-user/SageMaker/EtudeWindIndex/Data/Train_Test/hourly/testset.csv')
    trainset.to_csv(trainset_path, index=False, sep=';')
    testset.to_csv(testset_path, index=False, sep=';')

# Récupération des données 10min

In [34]:
list_projects_path = Path('/home/ec2-user/SageMaker/EtudeWindIndex/Data/list_projects.csv')
list_projects = pd.read_csv(list_projects_path,sep=';')

#On demande à l'utilisateur un nom de projet
project = str(input('Choissez le projet à traiter:'))

while project not in list_projects.project.tolist() :
    print("")
    print("Vous n'avez pas choisi un nom de projet existant")
    print("Voici des exemples de noms :")
    for example in list_projects.sample(5).project.tolist():
        print(example)
    print("")
    project = str(input('Choissez le projet à traiter:'))

Choissez le projet à extraire: AMEL

In [35]:
#Lecture de l'export horraire turbine
S3_bucket = 'edfred-edfre-sbx-eu-west-1-solar-radiation-data'
S3_real_folder = r'EtudeWindIndex/Real'
file = '10min_' + project
S3_real = f's3://{S3_bucket}/{S3_real_folder}/{file}.csv'
real_set = pd.read_csv(S3_real, sep=';')

In [36]:
#Visualisation
real_set.sample(5)

,project,turbine,year,month,day,hour,minute,active_power_avg,wind_speed_avg
376288,AMEL,3,2021,8,8,14,50,1531.710,10.36110
965800,AMEL,3,2021,11,2,9,20,287.676,5.72588
1378187,AMEL,5,2021,11,26,3,30,0.000,2.09947
1131844,AMEL,1,2021,7,20,0,0,964.267,9.54214
1378075,AMEL,1,2021,11,25,23,50,0.000,1.64865

# Fabrication des train set et test set

In [37]:
#Fabrication aléatoire du trainset et testset
#2/3 de train pour 1/3 de test
#On prend l'hyppthèse que les turbines des mêmes parcs sont comparables
trainset, testset = train_test_split(real_set, test_size=0.33, random_state=42, stratify=real_set.loc[:,['year','month']])

#Visualisation du trainset
trainset.head()

,project,turbine,year,month,day,hour,minute,active_power_avg,wind_speed_avg
165478,AMEL,1,2021,8,18,19,50,335.783,6.75114
1370411,AMEL,1,2021,11,15,8,20,650.016,7.78161
1124547,AMEL,4,2021,7,9,20,50,0.000,4.73475
1042718,AMEL,3,2021,8,18,5,10,180.451,5.18532
395051,AMEL,4,2021,9,3,16,20,0.000,3.31196

In [38]:
#Visualisation du testset
testset.head()

,project,turbine,year,month,day,hour,minute,active_power_avg,wind_speed_avg
1251246,AMEL,3,2021,9,1,20,10,1106.2200,9.07154
1099358,AMEL,1,2021,11,4,21,10,382.4430,6.96316
680639,AMEL,5,2021,5,4,7,50,2235.1600,11.96650
172157,AMEL,2,2021,8,28,2,30,72.0075,4.34048
591224,AMEL,5,2021,9,1,3,20,783.6740,8.43210

In [39]:
trainset_path = Path('/home/ec2-user/SageMaker/EtudeWindIndex/Data/Train_Test/hourly/trainset.csv')
testset_path = Path('/home/ec2-user/SageMaker/EtudeWindIndex/Data/Train_Test/hourly/testset.csv')
    
#Sauvegarde
trainset.to_csv(trainset_path, index=False, sep=';')
testset.to_csv(testset_path, index=False, sep=';')